export const magicExperiencesComparison = {
  close_up_magic: {
    title: "Close-Up Magic Experience Comparison",
    tiers: [
      {
        name: "Gold",
        label: "Gold",
        features: {
          sleight_of_hand_magic: true,
          cards_coins_rings_visual_magic: true,
          advanced_magic_effects: false,
          mind_reading_mentalism: false,
          psychological_illusions: false,
          interactive_hypnosis: false,
          interactive_guest_experiences: true,
          customized_magic: false,
          pre_event_planning_call: false,
          vip_or_brand_customization: false,
        },
        best_for: "Intimate gatherings",
      },
      {
        name: "Signature",
        label: "Signature",
        badge: "Most Popular",
        features: {
          sleight_of_hand_magic: true,
          cards_coins_rings_visual_magic: true,
          advanced_magic_effects: true,
          mind_reading_mentalism: true,
          psychological_illusions: true,
          interactive_hypnosis: true,
          interactive_guest_experiences: true,
          customized_magic: false,
          pre_event_planning_call: false,
          vip_or_brand_customization: false,
        },
        best_for: "Corporate and VIP events",
      },
      {
        name: "Diamond",
        label: "Diamond",
        features: {
          sleight_of_hand_magic: true,
          cards_coins_rings_visual_magic: true,
          advanced_magic_effects: true,
          mind_reading_mentalism: true,
          psychological_illusions: true,
          interactive_hypnosis: true,
          interactive_guest_experiences: true,
          customized_magic: true,
          pre_event_planning_call: true,
          vip_or_brand_customization: true,
        },
        best_for: "Luxury and high-profile events",
      },
    ],
  },
  stage_magic: {
    title: "Stage Magic Experience Comparison",
    tiers: [
      {
        name: "Gold",
        label: "Gold",
        features: {
          high_energy_stage_magic: true,
          visual_illusions: true,
          audience_participation: true,
          advanced_magic_effects: false,
          mind_reading: false,
          telepathy: false,
          interactive_hypnosis: false,
          customized_show: false,
          personalized_scripts: false,
          brand_integration: false,
          pre_event_planning_call: false,
        },
        best_for: "Entertainment focused events",
      },
      {
        name: "Signature",
        label: "Signature",
        badge: "Most Popular",
        features: {
          high_energy_stage_magic: true,
          visual_illusions: true,
          audience_participation: true,
          advanced_magic_effects: true,
          mind_reading: true,
          telepathy: true,
          interactive_hypnosis: true,
          customized_show: false,
          personalized_scripts: false,
          brand_integration: false,
          pre_event_planning_call: false,
        },
        best_for: "Corporate shows and galas",
      },
      {
        name: "Diamond",
        label: "Diamond",
        features: {
          high_energy_stage_magic: true,
          visual_illusions: true,
          audience_participation: true,
          advanced_magic_effects: true,
          mind_reading: true,
          telepathy: true,
          interactive_hypnosis: true,
          customized_show: true,
          personalized_scripts: true,
          brand_integration: true,
          pre_event_planning_call: true,
        },
        best_for: "High-end productions and luxury events",
      },
    ],
  },
};